<a href="https://colab.research.google.com/github/jeffersontm2/IA_ULEAM/blob/main/Numpy_IA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Import numpy as np and see the version

```
# Tiene formato de código
```



In [1]:
import numpy as np

print(np.__version__)

1.22.4


2. Create a 1D array of numbers from 0 to 9

In [2]:
import numpy as np

array_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


3. Create a 3×3 numpy array of all True’s

In [3]:
array_3x3 = np.full((3, 3), True, dtype=bool)

print(array_3x3)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


4. Extract all odd numbers from arr

In [5]:
odd_numbers = array_1d[array_1d % 2 != 0]

print(odd_numbers)

[1 3 5 7 9]


5. Replace all odd numbers in arr with -1

In [7]:
array_1d[array_1d % 2 != 0] = -1

print(array_1d)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


6. Convert a 1D array to a 2D array with 2 rows

In [8]:
arr_1d = np.array([1, 2, 3, 4, 5, 6])

arr_2d = np.reshape(arr_1d, (2, -1))

print(arr_2d)

[[1 2 3]
 [4 5 6]]


7. Stack arrays a and b vertically

In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

stacked = np.vstack((a, b))

print(stacked)

[[1 2 3]
 [4 5 6]]


8. Stack the arrays a and b horizontally.

In [10]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

vertical = np.hstack((a, b))

print(vertical)

[1 2 3 4 5 6]


9. Get all items between 5 and 10 from a.

In [12]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

resultado_5a_10 = a[(a >= 5) & (a <= 10)]

print(resultado_5a_10)

[ 5  6  7  8  9 10]


10. 10. How to make a python function that handles scalars to work on numpy arrays?
# Hint
# Desired Output:
#a = np.array([5, 7, 9, 8, 6, 4, 5])
#b = np.array([6, 3, 4, 8, 9, 7, 1])
#b = np.array([6, 3, 4, 8, 9, 7, 1])
#pair_max(a, b)
#array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

In [20]:
def pair_max(a, b):
    return np.maximum(a, b)
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
r = pair_max(a, b)
print(r)

[6 7 9 8 9 7 5]


11.Swap columns 1 and 2 in the array arr.

In [22]:
arr = np.array([[0, 1, 2],
                [3, 4, 5],
                [6, 7, 8]])
arr[:, [1, 2]] = arr[:, [2, 1]]

print(arr)

[[0 2 1]
 [3 5 4]
 [6 8 7]]


12. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and
# Hint
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]

In [23]:
arr = np.random.uniform(5, 10, size=(5, 3))

print(arr)

[[9.82189961 8.29557411 6.39188789]
 [9.68781972 7.5572701  8.12726762]
 [7.75633404 9.9879847  8.59104333]
 [8.31516429 6.38977587 5.16865381]
 [6.4924046  8.79311907 8.76043143]]
